<a href="https://colab.research.google.com/github/sriraksha-Prabhu/AML/blob/main/AML_assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/Iris.csv")
dataset=df
dataset

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        1
1      2            4.9           3.0            1.4           0.2        1
2      3            4.7           3.2            1.3           0.2        1
3      4            4.6           3.1            1.5           0.2        1
4      5            5.0           3.6            1.4           0.2        1
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [4]:
df.shape

(150, 6)

In [5]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [6]:
X = df.drop('Species',axis=1)
y = df['Species']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.35,random_state=10)

In [8]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [9]:
y_pred = dt.predict(X_test)
y_pred

array([0, 2, 1, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 1, 1, 2, 0, 1, 1, 1, 2, 2,
       2, 1, 0, 1, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 0, 1,
       0, 1, 0, 0, 2, 2, 0, 2, 0])

In [10]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
print(classification_report(y_test,y_pred))
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy score:",accuracy*100)
confusion_matrix(y_test,y_pred)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        17

    accuracy                           1.00        53
   macro avg       1.00      1.00      1.00        53
weighted avg       1.00      1.00      1.00        53

Accuracy score: 100.0

array([[21,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 17]])

In [11]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[21,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 17]])

**Diabetes Dataset**

In [12]:
df=pd.read_csv("/content/diabetes.csv")
ds=df
ds

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [13]:
df['Pregnancies'].max()

17

In [ ]:
x=ds.iloc[:,1:7].values
x

array([[148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627],
       [ 85.   ,  66.   ,  29.   ,   0.   ,  26.6  ,   0.351],
       [183.   ,  64.   ,   0.   ,   0.   ,  23.3  ,   0.672],
       ...,
       [121.   ,  72.   ,  23.   , 112.   ,  26.2  ,   0.245],
       [126.   ,  60.   ,   0.   ,   0.   ,  30.1  ,   0.349],
       [ 93.   ,  70.   ,  31.   ,   0.   ,  30.4  ,   0.315]])

In [14]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [15]:

df.duplicated().sum()

np.int64(0)

In [16]:
X = df.drop('Outcome',axis=1)
y = df['Outcome']

In [18]:
import numpy as np
np.array(X)

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [19]:
print(X.shape)
print(y.shape)

(768, 8)
(768,)

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_sc = sc.fit_transform(X)

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_sc,y,test_size=0.35,random_state=10)

In [22]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [23]:
y_pred = dt.predict(X_test)
y_pred

array([1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0])

In [24]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
print(classification_report(y_test,y_pred))
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy score:",accuracy*100)
confusion_matrix(y_test,y_pred)

              precision    recall  f1-score   support

           0       0.77      0.78      0.78       172
           1       0.60      0.60      0.60        97

    accuracy                           0.71       269
   macro avg       0.69      0.69      0.69       269
weighted avg       0.71      0.71      0.71       269

Accuracy score: 71.37546468401487

array([[134,  38],
       [ 39,  58]])